severity:
  - CRITICAL
  - HIGH
ignore-unfixed: true
exit-code: 1
scan:
  skip-dirs:
    - node_modules
    - .git
  scanners:
    - vuln
    - secret
    - config
vulnerability:
  type:
    - os
    - library